### PR TITLE
Fix inability to add a doctype

### LINKED ISSUE #20: DOCTYPE
It seems like `<!DOCTYPE html>` tags are going missing from the templates when rendered as HTML?

### PR DESCRIPTION
**Pull request by emhoracek**
tagstream-conduit doesn't support doctypes, so html-conduit doesn't include them in the output.

This commit adds a new special blank, `<doctype />`, which is filled in with the HTML5 doctype.

To fix #20

### CODE REVIEW

**Comment by emhoracek** [comment]
I also made it replace real doctypes with the fake doctype before parsing with html-conduit. This way users of the library don't have to worry about it (and the existing template will Just Work).

File: test/Spec.hs [hunk 1]
```diff
@@ -450,6 +451,17 @@ statefulTests =
                     ["default"]
          `shouldReturn` Just "12"
 
+doctypeTests :: SpecWith LarcenyHspecState
+doctypeTests = do
+  describe "doctypes" $ do
+    it "should render blank doctypes" $ do
+      "<doctype />" `shouldRenderM` "<!DOCTYPE html>"
```
Comment (dhartunian) [inline test/Spec.hs]: should we insert doctypes even when they're not included? i guess we're not really sure we're outputting valid html5 all the time.

File: src/Web/Larceny/Internal.hs [hunk 2]
```diff
@@ -109,6 +110,7 @@ process (currentNode:nextNodes) = do
   pcNodes .= nextNodes
   processedNode <-
     case currentNode of
+      X.NodeElement (X.Element "doctype" _ [])  -> return ["<!DOCTYPE html>"]
```
Comment (dhartunian) [inline src/Web/Larceny/Internal.hs]: newline afterwards?

File: test/Spec.hs (hunk 1 above)
Comment (emhoracek) [inline test/Spec.hs]: The thing I struggled with was, where do we insert the doctype? Larceny doesn't know anything about the total structure of the page, just whatever part it's rendering right now. I guess it could be outside of `process`, in `renderWith`:

```
renderWith :: Library s -> Substitutions s -> s -> Path -> IO (Maybe Text)
renderWith l sub s = (fmap .fmap) (flip (++) "<!DOCTYPE html>") (renderRelative l sub s [])
```

I haven't typechecked that but the general idea -- prepend the doctype after processing. Maybe simpler?
